run_desktop:
	python -m streamlit run Home.py

run_mobile:
	python -m streamlit run mobile_app.py

install:
	pip install -r requirements.txt

install_face_recognition:
	pip install cmake
	pip install dlib
	pip install face_recognition
